name: leaf_disease_detection_app
description: A Flutter app for leaf disease detection.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  image_picker: ^0.8.7+6
  image: ^4.0.17
  # Use a newer tflite_flutter that is compatible with recent Dart/Flutter SDKs
  tflite_flutter: ^0.12.1
  # permission_handler upgraded to v12 to ensure Android v2 embedding compatibility
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/leaf_disease_efficientnetb0.tflite
    - assets/labels.txt
