name: leaf_disease_detection_app
description: A Flutter app for leaf disease detection.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Added dependencies required by the project
  google_fonts: ^4.0.3
  image_picker: ^0.8.7+6
  image: ^4.0.17
  tflite_flutter: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/leaf_disease_efficientnetb0.tflite
    - assets/labels.txt
